### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by aoko-sys** [OpenAvikom/mr-webrtc-unity#1]
Assets\Scripts\WebSocketSignaler.cs(6,7): error CS0246: The type or namespace name 'WebSocketSharp' could not be found (are you missing a using directive or an assembly reference?)

Assets\Scripts\TCPSignaler.cs(11,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)

How to solve these bugs?

**Comment by aleneum** [comment]
Hello @aoko-sys,

> Assets\Scripts\WebSocketSignaler.cs(6,7): error CS0246: The type or namespace name 'WebSocketSharp' could not be found (are you missing a using directive or an assembly reference?)

this implies that `Plugins/WebSocketSharp/websocket-sharp.dll` has not been loaded correctly. Check the folder and library in your project view and verify that it is loaded for your platform.

<img width="499" alt="websocketcharp" src="https://user-images.githubusercontent.com/205986/99267483-4bc3f800-2824-11eb-95b1-02f5355080e3.png">


> Assets\Scripts\TCPSignaler.cs(11,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)

Newtonsoft's JSON parser is imported via `Packages/manifest.json`. You should check whether `manifest.json` has been correctly initialized (Window -> Package Manager): 

<img width="494" alt="newtonsoft" src="https://user-images.githubusercontent.com/205986/99267498-4f577f00-2824-11eb-9750-63f775324b57.png">

or -- if you use `TCPSignaler.cs` in your own project -- that your `manifest.json` contains

```json

  "scopedRegistries": [
   ...
    {
      "name": "Packages from jillejr",
      "url": "https://npm.cloudsmith.io/jillejr/newtonsoft-json-for-unity/",
      "scopes": [
        "jillejr"
      ]
    },
   ...
``` 

as well as 

```json
  "dependencies": {
...
    "jillejr.newtonsoft.json-for-unity": "12.0.201",
...
```

**Comment by aoko-sys** [comment]
my computer 
win10
inter(R) Core(TM)i7-8750H 
unity:2019.4.14f1c1(64-bi)
Hololens2

![image](https://user-images.githubusercontent.com/52449394/99327891-e1f42e80-28b5-11eb-88a2-24f99d35b0d9.png)

**Comment by aleneum** [comment]
The chosen architecture might be wrong. Can you set "CPU" in the Platform settings tab to "Any CPU" or "x64"?

**Comment by aoko-sys** [comment]
![image](https://user-images.githubusercontent.com/52449394/99368747-7da58f00-28f6-11eb-80af-378897c93c25.png)
I only have the x64 option

**Comment by aleneum** [comment]
Does it work in the Editor when you choose "x64" (and restart Unity just in case)?  There seem to be issue with "Any CPU" and Visual Studio 2015 and earlier ([Stackoverflow](https://stackoverflow.com/questions/29979047/windows-universal-app-no-any-cpu-configuration-for-windows-10)). Alternatively, you could try to delete the DLL from the plugin folder and add it again. Or you try to import it as a [Nuget](https://www.nuget.org/packages/WebSocketSharp) package (using [NuGetForUnity](https://github.com/GlitchEnzo/NuGetForUnity)). Or you have a look at the [Github repository](https://github.com/sta/websocket-sharp) directly.

**Comment by aoko-sys** [comment]
![image](https://user-images.githubusercontent.com/52449394/99380740-4ee2e500-2905-11eb-9797-d70f229dbc47.png)
I don't know how to solve this mistake. I'm making more and more mistakes.

![image](https://user-images.githubusercontent.com/52449394/99380843-73d75800-2905-11eb-95fa-8410abf10e4e.png)
Can you use TeamView to deal with it for me remotely?

**Comment by aoko-sys** [comment]
![YR@((HC%F5YJ1FBVQQ5G)0R](https://user-images.githubusercontent.com/52449394/99380994-a3866000-2905-11eb-92b8-a91a4135eded.png)
I don't know how to solve this mistake. I'm making more and more mistakes.

**Comment by aoko-sys** [comment]
![image](https://user-images.githubusercontent.com/52449394/99381050-b8fb8a00-2905-11eb-84cd-42971cb72553.png)
I don't know how to solve this mistake. I'm making more and more mistakes.

**Comment by aoko-sys** [comment]
![image](https://user-images.githubusercontent.com/52449394/99381107-c7e23c80-2905-11eb-8ddc-05d236e6e0b3.png)
Can you use TeamView to deal with it for me remotely?

**Comment by aleneum** [comment]
Okay, the NuGet hasnt been updated since 2016. Even though it has a higher version number (1.0.3) than the bundled DLL (1.0.2.21027) it might be outdated. Can you get https://github.com/sta/websocket-sharp to work in Unity in an isolated project? 

>  Can you use TeamView to deal with it for me remotely?

No, sorry. I am positive you are more than capable of figuring that one out on your own 👍

**Comment by aoko-sys** [comment]
![image](https://user-images.githubusercontent.com/52449394/99390405-8e183280-2913-11eb-8752-021092112fd1.png)
I have solved the previous bug, but I have encountered a new one.

**Comment by aleneum** [comment]
Here is another approach:

Clone the this repo branch `dev-sharp` into a new folder. It contains the source code version of `websocket-sharp`:

```
git clone https://github.com/OpenAvikom/mr-webrtc-unity -b dev-sharp
```

Generate the SSL certificate. You need OpenSSL for this. I installed it with [Chocolatey](https://chocolatey.org). When prompted for passwords, just hit enter: 

```
cd mr-webrtc-unity\UnityWebRTC\Assets\StreamingAssets\Certs
openssl req -config req.conf -x509 -newkey rsa:4096 -keyout localhost_key.pem -out localhost.pem -nodes -days 3650
openssl pkcs12 -export -in localhost.pem -inkey localhost_key.pem -out localhost.pfx.bin -nodes
```

Now open the folder/project `mr-webrtc-unity\UnityWebRTC` in Unity and switch the platform to UWP in `Build Settings`. Afterwards, open the Scene `SignalerExample` and switch the `Connection Type` of the `Launcher` object to WebSocket. Now you should be able to run the WebSocket Server in the Unity Editor.

**Comment by aleneum** [comment]
>  I have solved the previous bug, but I have encountered a new one.

You are almost there! This is not the correct WebSocketSharp version it seems. They changed their API a while ago. Try to checkout branch `dev-sharp` of this repo as mentioned in my previous post. It contains the current master branch version of WebSocketSharp but as source code. Alternatively you can just delete the WebSocketSharp dll and copy the `Assets/WebSocketSharp` folder into your project.

**Comment by aoko-sys** [comment]
![image](https://user-images.githubusercontent.com/52449394/99394868-8f992900-291a-11eb-9ba6-5475a90c4f05.png)
One last step away from success.Could you please tell me how to solve this bug? It stays here all the time and there is no image showing

**Comment by aleneum** [comment]
Oh, that's an actual bug (which hasnt been exposed in aiortc < 1.0). `pc.addIceCandidate(obj)` in line 75 of `cli.py` needs to be awaited:

```python
        elif isinstance(obj, RTCIceCandidate):
            await pc.addIceCandidate(obj)
```

I pushed the fix to `dev-sharp`. See f983352. 

Seems like this behaviour has been recently introduced ([ref](https://github.com/aiortc/aiortc/commit/31abde4c7f142527a2a59c76333aafe627d4b2c6))

**Comment by aoko-sys** [comment]
thank you very much!
Do you know whether Mixed Reality WebRTC ?also uses Python to catch the incoming video data

**Comment by aleneum** [comment]
I dont think there is any Python code in microsoft/MixedReality-WebRTC if that's what you referring to.

**Comment by aoko-sys** [comment]
Can python code in your project be used with Microsoft/MixedReality-Webrtc?

**Comment by aleneum** [comment]
Yes and no. No, since the official package does not provide neither a `TCPSignaler` nor a `WebSocketSignaler`. Yes, since the example project `UnityWebRTC` uses the official package and uses the very same peer classes as the official examples. You can use `RTCServer` to bridge that gap but when you want to use it with their Unity components, further adjustments need to be done.

**Comment by aoko-sys** [comment]
I deployed the project to the Hololens2 device, but I found that the TCP connection could not be made. Under Unity Play mode, I could connect to TCP normally.
![image](https://user-images.githubusercontent.com/52449394/99495026-f535f580-29ac-11eb-82e5-3fb4a42946ab.png)

**Comment by aleneum** [comment]
Connectivity issues with Unity and HoloLens are quite common unfortunately. Reserved port ranges and player capabilities, firewall settings and such a like. I'd suggest that you check whether you can connect to anything running on the HoloLens and then check whether different ports make a difference. Check whether the Internet and PrivateNetworkClientServer capabilties in the Unity Player Settings are enabled and maybe delete the whole build artifact and rebuild it from scratch.

**Comment by aoko-sys** [comment]
I guess the project deployment on the Hololens2 device is not running, causing Python to fail to connect

**Comment by Shra234** [comment]
@aleneum 
I deploy this project to hololens 1 but not able to connect by using localhost Python code from PC terminal. If I don't use hololens then it is working thought my PC webcam but how can I make it work by using hololens. Can you please guide me. The Unity code successfully deploy to hololens 1 but how to connect the Python code?

**Comment by aleneum** [comment]
@Shra234: There are many things that could cause this. You should check that you have chosen a resolution that is supported by HoloLens 1. Check the output of Visual Studio in Debug-Mode to get an idea if what's going wrong. Second, there could be a firewall issue that prevents your HoloLens from reaching the correct port on your machine. As I mentioned above: 

> Connectivity issues with Unity and HoloLens are quite common unfortunately. Reserved port ranges and player capabilities, firewall settings and such a like. I'd suggest that you check whether you can connect to anything running on the HoloLens and then check whether different ports make a difference. Check whether the Internet and PrivateNetworkClientServer capabilties in the Unity Player Settings are enabled and maybe delete the whole build artifact and rebuild it from scratch.

**Comment by TerryHanson** [comment]
@aoko-sys have you fixed it? I will help you to fix it if you want me to.

**Comment by aoko-sys** [comment]
@TerryHanson Thank you very much, I have solved the problem.

**Comment by aleneum** [comment]
nice! closing this then.
